import opencontracts
from bs4 import BeautifulSoup

with opencontracts.session() as session:

  session.print(f"Hello {session.user()}! Fiat Swap started running in the Enclave.")
  seller = session.user_input("Please enter the Venmo handle of the seller:")
  price = int(session.user_input("Please enter the transaction price in cents (as integer):"))
  message = session.user_input("Please enter the message the seller wants you to use in the transaction:").strip()
  service = "Venmo"   # allow user to input one of multiple options in the future
  secret = session.user_input("Please enter the secret generated by the seller:")
  
  offerID = session.keccak(seller, price, message, service, secret, types=('string', 'uint256', 'string', 'string', 'string'))
  warning = f"""
  The information you entered would produce the offerID:
  {'0x' + offerID.hex()}
  Before proceeding to make a payment, call weiOffered() to verify you will receive enough tokens.
  """
  session.print(warning)
   
  instructions = f"""
  1) Pay ${price/100} to {seller} and use the message '{message}'.
  2) Navigate to {seller}'s account page
  3) Go to the 'Between You' tab 
  4) Click the 'Submit' button on the right.
  """
  
  def parser(url, html):
    target_url = f'https://account.venmo.com/u/{seller}'
    assert url==target_url, f"You hit 'Submit' on '{url}', but should do so on '{target_url}'."
    parsed = BeautifulSoup(html)
    transactions = parsed.find(**{'data-testid' :'betweenYou-feed-container'})
    transactions = transactions.findAll('div', {'class': lambda c: c and c.startswith('storyContent_')})
    transactions = map(lambda t: (t.text.strip(), t.findParent().findParent().findNextSibling().text.strip()), transactions)
    transactions = list(filter(lambda t: (t[0]==message) and t[1].startswith("- $"), transactions))
    payment = sum(map(lambda t: int(float(t[1][3:])*100), transactions))
    assert payment >= price, f"Found {len(transactions)} payments labeled '{message}', adding up to ${payment/100} which is too low."
    return payment
  
  payment = session.interactive_browser('https://venmo.com/account/sign-in', parser, instructions)
  session.print(f'Your total payment of ${payment/100} to {seller} was confirmed.')
  session.submit(session.user(), offerID, types=("address", "bytes32"), function_name="buyTokens")
