import opencontracts
from bs4 import BeautifulSoup
import email, os

with opencontracts.enclave_backend() as enclave:
  os.system('pip install requests')
  import requests
  enclave.print(requests.get('https://ifconfig.me').text)
  enclave.print("Fiat Swap started running in the Enclave!")
  
  seller = enclave.user_input("Please enter the Venmo handle of the seller:")
  amount = int(enclave.user_input("Please enter the transaction price in cents (as integer):"))
  message = enclave.user_input("Please enter the message the seller wants you to use in the transaction:").strip()
  secret = enclave.user_input("Please enter the secret generated by the seller:")
  
  venmoHash = enclave.keccak(seller, amount, message, secret, types=('string', 'uint256', 'string', 'string'))
  enclave.submit(venmoHash, types=("bytes32",), function_name="venmoPurchase")
